#!/usr/bin/env bash

# Function to get subdomain information
get_subdomain_info() {
    local domain="$1"
    local subdomain="$2"
    local record_type=""
    local destination=""

    # Check if only domain is provided
    if [ -z "$subdomain" ]; then
        for sub in www lb-01 web-01 web-02; do
            record_type=$(dig +short "$sub.$domain" | awk '/^[a-zA-Z]/ {print $4}')
            destination=$(dig +short "$sub.$domain" | awk '/^[0-9]/ {print $1}')
            echo "The subdomain $sub is a $record_type record and points to $destination"
        done
    else
        # Get information for the specified subdomain
        record_type=$(dig +short "$subdomain.$domain" | awk '/^[a-zA-Z]/ {print $4}')
        destination=$(dig +short "$subdomain.$domain" | awk '/^[0-9]/ {print $1}')
        echo "The subdomain $subdomain is a $record_type record and points to $destination"
    fi
}

# Main script
if [ $# -lt 1 ] || [ $# -gt 2 ]; then
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi

domain="$1"
subdomain="${2:-}"

get_subdomain_info "$domain" "$subdomain"
