#!/usr/bin/env bash

# Function to get subdomain information
get_subdomain_info() {
    local domain="$1"
    local subdomain="$2"

    if [ -z "$subdomain" ]; then
        for sub in www lb-01 web-01 web-02; do
            dig "$sub.$domain" | awk '
                $0==";;\ ANSWER\ SECTION:" {f=1; next}
                !NF {f=0;}
                f {split($1, a, "."); print "The subdomain", a[1], "is a", $4, "record and points to", $5}'
        done
    else
        dig "$subdomain.$domain" | awk '
            $0==";;\ ANSWER\ SECTION:" {f=1; next}
            !NF {f=0;}
            f {split($1, a, "."); print "The subdomain", a[1], "is a", $4, "record and points to", $5}'
    fi
}

# Main script
if [ $# -lt 1 ] || [ $# -gt 2 ]; then
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi

domain="$1"
subdomain="${2:-}"

get_subdomain_info "$domain" "$subdomain"
