#!/usr/bin/env bash

# Function to display information about a subdomain
display_subdomain_info() {
    local subdomain=$1
    local domain=$2

    # Retrieve DNS information for the subdomain
    dns_info=$(dig +short $subdomain.$domain)

    # Determine the record type
    if [[ -n "$dns_info" ]]; then
        record_type=$(echo "$dns_info" | awk '{ if (NR==1) {print "A";} else {print "CNAME";}}')
        destination=$(echo "$dns_info" | awk 'NR==1{print $1}')
        echo "The subdomain $subdomain is a $record_type record and points to $destination"
    else
        echo "The subdomain $subdomain does not exist for domain $domain"
    fi
}

# Main function to handle command line arguments
main() {
    local domain=$1
    local subdomain=$2

    if [[ -z $subdomain ]]; then
        # Display information for default subdomains
        display_subdomain_info www $domain
        display_subdomain_info lb-01 $domain
        display_subdomain_info web-01 $domain
        display_subdomain_info web-02 $domain
    else
        # Display information for the specified subdomain
        display_subdomain_info $subdomain $domain
    fi
}

# Check if required arguments are provided
if [[ $# -lt 1 ]]; then
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

main "$@"
