#!/usr/bin/env bash
#displays the time for 12 hours and 59 minutes:
#display hours from 0 to 12
#display minutes from 1 to 59

hours=0
while [[ $hours -le 12 ]]; do
    minutes=0
    while [[ $minutes -lt 60 ]]; do
        if [[ $minutes -lt 10 ]]; then
            minutes=0$minutes
        fi
        echo "$hours:$minutes" 
        ((minutes++))
    done 
    ((hours++))
done
