#!/usr/bin/env bash
#install the ufw firewall and setup a few rules on web-01
sudo apt install -y ufw
sudo ufw --force enable
sudo ufw default deny incoming
sudo ufw allow 80
sudo ufw allow 443
sudo ufw allow 22
sudo service ufw restart
